config/routes.rb
Rails.application.routes.draw do
  root to: 'houses#index'
  resources :homes
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/home.rb
class Home < ApplicationRecord
  validates :name, presence: true, length:{maximum:30}
  validates :rent, presence: true
  validates :address, presence: true, length:{maximum:50}
  validates :year, presence: true

  has_many:stations, dependent: :destroy
  accepts_nested_attributes_for :stations, allow_destroy: true
end

app/models/station.rb
class Station < ApplicationRecord
  validates :line, presence: false
  validates :station, presence: false
  validates :minute, presence: false

  belongs_to :house
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  before_action :set_home, only: %i(show edit update destroy)

  def index
    @homes = Home.all
  end

  def new
    @home = Home.new
    @home.stations.build
  end

  def create
    @home = Home.new(home_params)
    if params[:back]
      render :new # これがないと、create.html.erbを表示しようとする
    else
      if @home.save
        redirect_to homes_path,  notice:"登録しました!！"
      else
        render :new
      end
    end
  end

  def show
  end

  def edit
    if @home.stations.last.minute.blank? &&
       @home.stations.last.line.blank? &&
       @home.stations.last.station.blank?
    else
       @home.stations.build
    end
  end

  def update
    if @home.update(home_params)
      redirect_to homes_path, notice:"編集しました！"
    else
      render :edit
    end
  end

  def destroy
    @home.destroy
    redirect_to homes_path, notice:"削除しました！"
  end

  private

  def set_home
    @home  = Home.find(params[:id])
  end

  def home_params
    params.require(:home).permit(:name, :rent, :address, :year, :remarks,
                                  stations_attributes: %i(id line station minute house_id))
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/homes/_form.html.erb
<%= form_with(model: home, local: true) do |form| %>
  <% if home.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(home.errors.count, "error") %> prohibited this home from being saved:</h2>

      <ul>
      <% home.errors.full_messages.each do |message| %>
        <td><%= message %></td>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :物件名 %>
    <%= form.text_field :name, placeholder:"例：〇〇マンション" %>
  </div>

  <div class="field">
    <%= form.label :rent, "賃料" %>
    <%= form.number_field :rent %>円
  </div>

  <div class="field">
    <%= form.label :address, "住所" %>
    <%= form.text_field :address, placeholder:"例：東京都XXXX" %>
  </div>

  <div class="field">
    <%= form.label :year, "築年数" %>
    <%= form.number_field :year %>年
  </div>

  <div class="field">
    <%= form.label :備考 %>
    <%= form.text_area :remarks %>
  </div>

<span>-----------------------------------------</span>
<% n = 0 %>
<%= form.fields_for :stations do |station| %>
  <h3>最寄り駅<%= n += 1 %></h3>
    <tr>
      <td><%= station.label :路線名 %></td>
      <td><%= station.text_field :line %></td>
      <td><%= station.label :駅名 %></td>
      <td><%= station.text_field :station %></td>
      <td><%= station.label :徒歩分数 %></td>
      <td><%= station.text_field :minute %>分</td>
    </tr>
<% end %>

    <div class="actions">
      <%= form.submit "登録する" %>
    </div>
<% end %>

app/views/homes/edit.html.erb
<h1>物件編集</h1>

<%= render 'form', home: @home %>

<%= link_to '詳細', home_path %> |
<%= link_to '戻る', homes_path %>

app/views/homes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>物件一覧</h1>

<table>
  <thead>
    <tr>
      <th>物件名</th>
      <th>賃料</th>
      <th>住所</th>
      <th>築年数</th>
      <th>備考</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @homes.each do |home| %>
      <tr>
        <td><%= home.name %></td>
        <td><%= home.rent %>円</td>
        <td><%= home.address %></td>
        <td><%= home.year %>年</td>
        <td><%= home.remarks %></td>
        <td><%= link_to '詳細', home %></td>
        <td><%= link_to '編集', edit_home_path(home) %></td>
        <td><%= link_to '削除', home, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to '物件を登録する', new_home_path %>

app/views/homes/new.html.erb
<h1>物件登録</h1>

<%= render 'form', home: @home, station: @station %>

<%= link_to '戻る', homes_path %>

app/views/homes/show.html.erb
<p id="notice"><%= notice %></p>

<h1>閲覧</h1>
<p>
  <strong>物件名:</strong>
  <%= @home.name %>
</p>

<p>
  <strong>賃料:</strong>
  <%= @home.rent %>円
</p>

<p>
  <strong>住所:</strong>
  <%= @home.address %>
</p>

<p>
  <strong>築年数:</strong>
  <%= @home.year %>円
</p>

<p>
  <strong>備考:</strong>
  <%= @home.remarks %>
</p>

<p>--------------------------------------- </p>

<% n = 0 %>
  <% @home.stations.each do |station|%>
      <% if station.line.blank? && station.station.blank? && station.minute.blank? %>
        <p>最寄り駅の情報はありません！</p>
      <% else %>
      <h3>最寄り駅<%= n += 1 %></h3>
        <tr>
          <td>路線名:<%= station.line %></td>
          <td>駅名：<%= station.station %></td>
          <td>徒歩分数：<%= station.minute %>分</td>
        </tr>
      <% end %>
  <% end %>

<%= link_to '編集', edit_home_path %> |
<%= link_to '戻る', homes_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DevExam</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>